[program:broker_connector]
command=/usr/bin/env python -m services.broker_connector.service %(ENV_FLAGS)s
environment=PYTHONPATH=".",PYTHONUNBUFFERED="1"
stdout_logfile=log/broker_connector.log
redirect_stderr=true
